### ISSUE TITLE
Running dupes give points in the log - ideally shouldn't be so

### ISSUE THREAD

**Issue by awandahl** [mbridak/not1mm#155]
**Is your feature request related to a problem? Please describe.**

Running a station again (a so called dupe) in a contest is not necessarily a bad thing. It's usually convenient not to get into a discussion if "worked B4" is true or not, easier just to run the station again and get rid of the problem. But it's also necessary that you on your side indicates that it is a dupe. This is usually done by putting 0 points in the log.

**Describe the solution you'd like**
Running a dupe should register 0 points in the log for the QSO.

**Describe alternatives you've considered**
Makin a note somewhere and edit by hand afterwards. Not very practical.

**Comment by awandahl** [comment]
For CQWW CW, does this make sense?
```
def points(self):
    """Calc point"""
    # Retrieve callsign and band information
    call = self.contact.get("Call", "")
    band = float(get_logged_band(str(self.contact.get("Freq", 0.0))))
    
    # Check if the contact is a duplicate on the current band
    dupe_check = self.database.check_dupe_on_band(call, band)
    if dupe_check.get("isdupe", 0) > 0:
        return 0  # Return zero points for duplicates

    result = self.cty_lookup(self.station.get("Call", ""))
    if result:
        for item in result.items():
            mycountry = item[1].get("entity", "")
            mycontinent = item[1].get("continent", "")
    result = self.cty_lookup(self.contact.get("Call", ""))
    if result:
        for item in result.items():
            entity = item[1].get("entity", "")
            continent = item[1].get("continent", "")
            if mycountry.upper() == entity.upper():
                return 0
            if mycontinent and continent == "NA":
                return 2
            if mycontinent == continent:
                return 1
            return 3
    return 0
```

**Comment by mbridak** [comment]
Looks good. I'd merge that.

**Comment by awandahl** [comment]
No, it doesn't work. I have problems finding out how to call the database apparently:
```
(not1mm) aw@HP-ZBook:~/exp_not1mm/not1mm-master$ python -m not1mm
Traceback (most recent call last):
  File "/home/aw/exp_not1mm/not1mm-master/not1mm/__main__.py", line 709, in check_esm_with_enter
    self.contest.process_esm(self, with_enter=True)
  File "/home/aw/exp_not1mm/not1mm-master/not1mm/plugins/cq_ww_cw.py", line 461, in process_esm
    self.save_contact()
  File "/home/aw/exp_not1mm/not1mm-master/not1mm/__main__.py", line 2251, in save_contact
    self.contact["Points"] = self.contest.points(self)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aw/exp_not1mm/not1mm-master/not1mm/plugins/cq_ww_cw.py", line 155, in points
    band = float(get_logged_band(str(self.contact.get("Freq", 0.0))))
                 ^^^^^^^^^^^^^^^
NameError: name 'get_logged_band' is not defined
``

**Comment by awandahl** [comment]
This beats me! Am I even close??? At least this one doesn't throw any errors but it doesn't work either. And I can't find any log output.
```
def points(self):
    """Calc point"""
    # Retrieve callsign
    call = self.contact.get("Call", "")
    # Use predefined band setting
    band = self.contest_settings.get("BandCategory", "")

    # Check if the contact is a duplicate on the current band
    dupe_check = self.database.check_dupe_on_band(call, band)
    if dupe_check.get("isdupe", 0) > 0:
        return 0  # Return zero points for duplicates

    result = self.cty_lookup(self.station.get("Call", ""))
    if result:
        for item in result.items():
            mycountry = item[1].get("entity", "")
            mycontinent = item[1].get("continent", "")
    result = self.cty_lookup(self.contact.get("Call", ""))
    if result:
        for item in result.items():
            entity = item[1].get("entity", "")
            continent = item[1].get("continent", "")
            if mycountry.upper() == entity.upper():
                return 0
            if mycontinent and continent == "NA":
                return 2
            if mycontinent == continent:
                return 1
            return 3
    return 0
``

**Comment by mbridak** [comment]
Nope, you were closer with the first one. The logic is sound. You just have to carefully look at the thrown error.
Fix why the error happened, then if it still doesn't work there must be something wrong with the data.
So you need to look at what the supporting functions need and compare that with the data your feeding them.

So the very first thing you saw was:

```python
NameError: name 'get_logged_band' is not defined
```

So the `points` function doesn't know about the get_logged_band function. To fix that you import it. so you can add:

```python
from not1mm.lib.ham_utility import get_logged_band
```  

near the top where the other imports are. This will stop the crashes, but it still isn't doing what we're asking of it. So the data must be wrong. So we have to look at the data that we're providing to the functions. So just add a little print statement to dump the values we want to see. So after you get the value for dupe_check you can add something like:

```python
print(f"{call=} {band=} {dupe_check=} {self.contact=}")
```

and you'll get:

```text
call='M0MCX' band=0.0 dupe_check={'isdupe': 0} self.contact={'TS': '2024-10-24 14:51:06', 'Call': 'M0MCX', 
'Freq': 14030.7, 'QSXFreq': 14030.7, 'Mode': 'CW', 'ContestName': 'CQ-WW-CW', 'SNT': '599', 'RCV': '599', 
...More stuff truncated for brevity
```

Okay. So we can see that `band` is 0.0, so the problem most likely what we're feeding the `get_logged_band` function. We can look there to see what it expects from us. The doc string for `get_logged_band` says:

```text
    Convert a (string) frequency into a (string) band.
    Returns a (string) band.
    Returns a "0" if frequency is out of band.
```

And a code snippet from it:

```python
if 14350000 > frequency > 14000000:
    return "14"
```

Shows that it's working with frequencies in Hz. But the print statement shows that we are feeding it from `'Freq': 14030.7` which is a float in Khz. We just need to do some data conversion. So:

```python
band = float(get_logged_band(str(self.contact.get("Freq", 0.0))))
```

becomes:

```python
band = float(get_logged_band(str(int(self.contact.get("Freq", 0.0) * 1000))))
``` 

Now we should be feeding the function the correct data and getting some useful work out of the function. Our debug print now gives us:

```python
call='M0MCX' band=14.0 dupe_check={'isdupe': 1}
```

Now the `band` has a good value and the dupe_check is working.

![image](https://github.com/user-attachments/assets/28e4221e-6ddb-4271-876d-16edaf0afecc)

As we can see above, the first time the qso gives points, and the second does not.

**Comment by awandahl** [comment]
Wow! So this is it! Indeed seems to work. Thanks for the pedagogical explanation! I learnt a lot!
```
"""CQ World Wide DX CW plugin"""

# CQ Worldwide DX Contest, CW
#  	Status:	Active
#  	Geographic Focus:	Worldwide
#  	Participation:	Worldwide
#  	Awards:	Worldwide
#  	Mode:	CW
#  	Bands:	160, 80, 40, 20, 15, 10m
#  	Classes:	Single Op All Band (QRP/Low/High)
# Single Op Single Band (QRP/Low/High)
# Single Op Assisted All Band (QRP/Low/High)
# Single Op Assisted Single Band (QRP/Low/High)
# Single Op Overlays: (Classic/Rookie/Youth)
# Multi-Single (Low/High)
# Multi-Two
# Multi-Multi
# Explorer
#  	Max power:	HP: 1500 watts
# LP: 100 watts
# QRP: 5 watts
#  	Exchange:	RST + CQ Zone No.
#  	Work stations:	Once per band
#  	QSO Points:	0 points per QSO with same country (counts as mult)
# 1 point per QSO with different country same continent
# 2 points per QSO with different country same continent (NA)
# 3 points per QSO with different continent
#  	Multipliers:	Each CQ zone once per band
# Each country once per band
#  	Score Calculation:	Total score = total QSO points x total mults
#  	E-mail logs to:	(none)
#  	Upload log at:	https://www.cqww.com/logcheck/
#  	Mail logs to:	(none)
#  	Find rules at:	https://www.cqww.com/rules.htm
#  	Cabrillo name:	CQ-WW-CW

# pylint: disable=invalid-name, unused-argument, unused-variable, c-extension-no-member, unused-import

import datetime
import logging

from pathlib import Path

from PyQt6 import QtWidgets

from not1mm.lib.plugin_common import gen_adif, get_points
from not1mm.lib.version import __version__
from not1mm.lib.ham_utility import get_logged_band

logger = logging.getLogger(__name__)

EXCHANGE_HINT = "CQ Zone No."

name = "CQ WW CW"
cabrillo_name = "CQ-WW-CW"
mode = "CW"  # CW SSB BOTH RTTY
# columns = [0, 1, 2, 3, 4, 5, 6, 15]
columns = [
    "YYYY-MM-DD HH:MM:SS",
    "Call",
    "Freq",
    "Snt",
    "Rcv",
    "SentNr",
    "RcvNr",
    "PTS",
]

advance_on_space = [True, True, True, True, True]

# 1 once per contest, 2 work each band, 3 each band/mode, 4 no dupe checking
dupe_type = 2


def init_contest(self):
    """setup plugin"""
    set_tab_next(self)
    set_tab_prev(self)
    interface(self)
    self.next_field = self.other_2


def interface(self):
    """Setup user interface"""
    self.field1.show()
    self.field2.show()
    self.field3.hide()
    self.field4.show()
    self.snt_label.setText("SNT")
    self.field1.setAccessibleName("RST Sent")
    label = self.field4.findChild(QtWidgets.QLabel)
    label.setText("CQ Zone")
    self.field4.setAccessibleName("C Q Zone")


def reset_label(self):
    """reset label after field cleared"""


def set_tab_next(self):
    """Set TAB Advances"""
    self.tab_next = {
        self.callsign: self.field1.findChild(QtWidgets.QLineEdit),
        self.field1.findChild(QtWidgets.QLineEdit): self.field2.findChild(
            QtWidgets.QLineEdit
        ),
        self.field2.findChild(QtWidgets.QLineEdit): self.field4.findChild(
            QtWidgets.QLineEdit
        ),
        self.field3.findChild(QtWidgets.QLineEdit): self.callsign,
        self.field4.findChild(QtWidgets.QLineEdit): self.callsign,
    }


def set_tab_prev(self):
    """Set TAB Advances"""
    self.tab_prev = {
        self.callsign: self.field4.findChild(QtWidgets.QLineEdit),
        self.field1.findChild(QtWidgets.QLineEdit): self.callsign,
        self.field2.findChild(QtWidgets.QLineEdit): self.field1.findChild(
            QtWidgets.QLineEdit
        ),
        self.field3.findChild(QtWidgets.QLineEdit): self.field2.findChild(
            QtWidgets.QLineEdit
        ),
        self.field4.findChild(QtWidgets.QLineEdit): self.field2.findChild(
            QtWidgets.QLineEdit
        ),
    }


def set_contact_vars(self):
    """Contest Specific"""
    self.contact["SNT"] = self.sent.text()
    self.contact["RCV"] = self.receive.text()
    self.contact["ZN"] = self.other_2.text()
    self.contact["NR"] = self.other_2.text()
    self.contact["SentNr"] = self.contest_settings.get("SentExchange", 0)


def predupe(self):
    """called after callsign entered"""


def prefill(self):
    """Fill CQ Zone"""
    if len(self.other_2.text()) == 0:
        self.other_2.setText(str(self.contact.get("ZN", "")))
    self.other_1.setText(str(self.contest_settings.get("SentExchange", 0)))


def points(self):
    """Calc point"""
    # Retrieve callsign and band information
    call = self.contact.get("Call", "")
    band = float(get_logged_band(str(int(self.contact.get("Freq", 0.0) * 1000))))
    
    # Check if the contact is a duplicate on the current band
    dupe_check = self.database.check_dupe_on_band(call, band)
    if dupe_check.get("isdupe", 0) > 0:
        return 0  # Return zero points for duplicates

    result = self.cty_lookup(self.station.get("Call", ""))
    if result:
        for item in result.items():
            mycountry = item[1].get("entity", "")
            mycontinent = item[1].get("continent", "")
    result = self.cty_lookup(self.contact.get("Call", ""))
    if result:
        for item in result.items():
            entity = item[1].get("entity", "")
            continent = item[1].get("continent", "")
            if mycountry.upper() == entity.upper():
                return 0
            if mycontinent and continent == "NA":
                return 2
            if mycontinent == continent:
                return 1
            return 3
    return 0


def show_mults(self):
    """Return display string for mults"""
    result1 = self.database.fetch_zn_band_count()
    result2 = self.database.fetch_country_band_count()
    if result1 and result2:
        return int(result1.get("zb_count", 0)) + int(result2.get("cb_count", 0))
    return 0


def show_qso(self):
    """Return qso count"""
    result = self.database.fetch_qso_count()
    if result:
        return int(result.get("qsos", 0))
    return 0


def calc_score(self):
    """Return calculated score"""
    result = self.database.fetch_points()
    if result is not None:
        score = result.get("Points", "0")
        if score is None:
            score = "0"
        contest_points = int(score)
        mults = show_mults(self)
        return contest_points * mults
    return 0


def adif(self):
    """Call the generate ADIF function"""
    gen_adif(self, cabrillo_name, "CQ-WW-CW")


def cabrillo(self):
    """Generates Cabrillo file. Maybe."""
    # https://www.cqwpx.com/cabrillo.htm
    logger.debug("******Cabrillo*****")
    logger.debug("Station: %s", f"{self.station}")
    logger.debug("Contest: %s", f"{self.contest_settings}")
    now = datetime.datetime.now()
    date_time = now.strftime("%Y-%m-%d_%H-%M-%S")
    filename = (
        str(Path.home())
        + "/"
        + f"{self.station.get('Call', '').upper()}_{cabrillo_name}_{date_time}.log"
    )
    logger.debug("%s", filename)
    log = self.database.fetch_all_contacts_asc()
    try:
        with open(filename, "w", encoding="ascii") as file_descriptor:
            print("START-OF-LOG: 3.0", end="\r\n", file=file_descriptor)
            print(
                f"CREATED-BY: Not1MM v{__version__}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"CONTEST: {cabrillo_name}",
                end="\r\n",
                file=file_descriptor,
            )
            if self.station.get("Club", ""):
                print(
                    f"CLUB: {self.station.get('Club', '').upper()}",
                    end="\r\n",
                    file=file_descriptor,
                )
            print(
                f"CALLSIGN: {self.station.get('Call','')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"LOCATION: {self.station.get('ARRLSection', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            # print(
            #     f"ARRL-SECTION: {self.pref.get('section', '')}",
            #     end="\r\n",
            #     file=file_descriptor,
            # )
            print(
                f"CATEGORY-OPERATOR: {self.contest_settings.get('OperatorCategory','')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"CATEGORY-ASSISTED: {self.contest_settings.get('AssistedCategory','')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"CATEGORY-BAND: {self.contest_settings.get('BandCategory','')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"CATEGORY-MODE: {self.contest_settings.get('ModeCategory','')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"CATEGORY-TRANSMITTER: {self.contest_settings.get('TransmitterCategory','')}",
                end="\r\n",
                file=file_descriptor,
            )
            if self.contest_settings.get("OverlayCategory", "") != "N/A":
                print(
                    f"CATEGORY-OVERLAY: {self.contest_settings.get('OverlayCategory','')}",
                    end="\r\n",
                    file=file_descriptor,
                )
            print(
                f"GRID-LOCATOR: {self.station.get('GridSquare','')}",
                end="\r\n",
                file=file_descriptor,
            )
            # print(
            #     f"CATEGORY: {None}",
            #     end="\r\n",
            #     file=file_descriptor,
            # )
            print(
                f"CATEGORY-POWER: {self.contest_settings.get('PowerCategory','')}",
                end="\r\n",
                file=file_descriptor,
            )

            print(
                f"CLAIMED-SCORE: {calc_score(self)}",
                end="\r\n",
                file=file_descriptor,
            )
            ops = f"@{self.station.get('Call','')}"
            list_of_ops = self.database.get_ops()
            for op in list_of_ops:
                ops += f", {op.get('Operator', '')}"
            print(
                f"OPERATORS: {ops}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"NAME: {self.station.get('Name', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"ADDRESS: {self.station.get('Street1', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"ADDRESS-CITY: {self.station.get('City', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"ADDRESS-STATE-PROVINCE: {self.station.get('State', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"ADDRESS-POSTALCODE: {self.station.get('Zip', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"ADDRESS-COUNTRY: {self.station.get('Country', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            print(
                f"EMAIL: {self.station.get('Email', '')}",
                end="\r\n",
                file=file_descriptor,
            )
            for contact in log:
                the_date_and_time = contact.get("TS", "")
                themode = contact.get("Mode", "")
                if themode == "LSB" or themode == "USB":
                    themode = "PH"
                frequency = str(int(contact.get("Freq", "0"))).rjust(5)

                loggeddate = the_date_and_time[:10]
                loggedtime = the_date_and_time[11:13] + the_date_and_time[14:16]
                print(
                    f"QSO: {frequency} {themode} {loggeddate} {loggedtime} "
                    f"{contact.get('StationPrefix', '').ljust(13)} "
                    f"{str(contact.get('SNT', '')).ljust(3)} "
                    f"{str(contact.get('SentNr', '')).ljust(6)} "
                    f"{contact.get('Call', '').ljust(13)} "
                    f"{str(contact.get('RCV', '')).ljust(3)} "
                    f"{str(contact.get('ZN', '')).ljust(6)}",
                    end="\r\n",
                    file=file_descriptor,
                )
            print("END-OF-LOG:", end="\r\n", file=file_descriptor)
        self.show_message_box(f"Cabrillo saved to: {filename}")
    except IOError as exception:
        logger.critical("cabrillo: IO error: %s, writing to %s", exception, filename)
        self.show_message_box(f"Error saving Cabrillo: {exception} {filename}")
        return


def recalculate_mults(self):
    """Recalculates multipliers after change in logged qso."""


def process_esm(self, new_focused_widget=None, with_enter=False):
    """ESM State Machine"""

    # self.pref["run_state"]

    # -----===== Assigned F-Keys =====-----
    # self.esm_dict["CQ"]
    # self.esm_dict["EXCH"]
    # self.esm_dict["QRZ"]
    # self.esm_dict["AGN"]
    # self.esm_dict["HISCALL"]
    # self.esm_dict["MYCALL"]
    # self.esm_dict["QSOB4"]

    # ----==== text fields ====----
    # self.callsign
    # self.sent
    # self.receive
    # self.other_1
    # self.other_2

    if new_focused_widget is not None:
        self.current_widget = self.inputs_dict.get(new_focused_widget)

    # print(f"checking esm {self.current_widget=} {with_enter=} {self.pref.get("run_state")=}")

    for a_button in [
        self.esm_dict["CQ"],
        self.esm_dict["EXCH"],
        self.esm_dict["QRZ"],
        self.esm_dict["AGN"],
        self.esm_dict["HISCALL"],
        self.esm_dict["MYCALL"],
        self.esm_dict["QSOB4"],
    ]:
        if a_button is not None:
            self.restore_button_color(a_button)

    buttons_to_send = []

    if self.pref.get("run_state"):
        if self.current_widget == "callsign":
            if len(self.callsign.text()) < 3:
                self.make_button_green(self.esm_dict["CQ"])
                buttons_to_send.append(self.esm_dict["CQ"])
            elif len(self.callsign.text()) > 2:
                self.make_button_green(self.esm_dict["HISCALL"])
                self.make_button_green(self.esm_dict["EXCH"])
                buttons_to_send.append(self.esm_dict["HISCALL"])
                buttons_to_send.append(self.esm_dict["EXCH"])

        elif self.current_widget == "other_2":
            if self.other_2.text() == "":
                self.make_button_green(self.esm_dict["AGN"])
                buttons_to_send.append(self.esm_dict["AGN"])
            elif self.other_2.text().isnumeric():
                self.make_button_green(self.esm_dict["QRZ"])
                buttons_to_send.append(self.esm_dict["QRZ"])
                buttons_to_send.append("LOGIT")
            else:
                self.make_button_green(self.esm_dict["AGN"])
                buttons_to_send.append(self.esm_dict["AGN"])

        if with_enter is True and bool(len(buttons_to_send)):
            for button in buttons_to_send:
                if button:
                    if button == "LOGIT":
                        self.save_contact()
                        continue
                    self.process_function_key(button)
    else:
        if self.current_widget == "callsign":
            if len(self.callsign.text()) > 2:
                self.make_button_green(self.esm_dict["MYCALL"])
                buttons_to_send.append(self.esm_dict["MYCALL"])

        elif self.current_widget == "other_2":
            if self.other_2.text() == "":
                self.make_button_green(self.esm_dict["AGN"])
                buttons_to_send.append(self.esm_dict["AGN"])
            elif self.other_2.text().isnumeric():
                self.make_button_green(self.esm_dict["EXCH"])
                buttons_to_send.append(self.esm_dict["EXCH"])
                buttons_to_send.append("LOGIT")
            else:
                self.make_button_green(self.esm_dict["AGN"])
                buttons_to_send.append(self.esm_dict["AGN"])

        if with_enter is True and bool(len(buttons_to_send)):
            for button in buttons_to_send:
                if button:
                    if button == "LOGIT":
                        self.save_contact()
                        continue
                    self.process_function_key(button)
```

**Comment by mbridak** [comment]
No problem. Glad to help. and I learned a new word, pedagogical, :+1: 

I've committed the changes and pushed 24-10-24.
I'll close this as complete.
