### ISSUE TITLE
Crash when no Q's entered and ESC pressed causing non existing points to be recalculated.

### ISSUE THREAD

**Issue by mbridak** [mbridak/not1mm#62]
```
Traceback (most recent call last):
  File "/home/mbridak/Nextcloud/dev/not1mm/not1mm/__main__.py", line 1075, in keyPressEvent
    self.clearinputs()
  File "/home/mbridak/Nextcloud/dev/not1mm/not1mm/__main__.py", line 1257, in clearinputs
    score = self.contest.calc_score(self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mbridak/Nextcloud/dev/not1mm/not1mm/plugins/winter_field_day.py", line 144, in calc_score
    _points = get_points(self)
              ^^^^^^^^^^^^^^^^
  File "/home/mbridak/Nextcloud/dev/not1mm/not1mm/plugins/winter_field_day.py", line 138, in get_points
    return int(result.get("Points", "0"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by mbridak** [comment]
{'Points': None}

**Comment by mbridak** [comment]
pushed fix with 23-12-4.
